In [ ]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [ ]:
website = 'www.yourwebsite.com' #Paste Your Website Link

In [ ]:
response = requests.get(website)

In [ ]:
response.status_code

200

In [ ]:
soup = BeautifulSoup(response.content,'html.parser')

In [ ]:
results = soup.find_all(('article', {'class': '_68441e28'}))

In [ ]:
len(results)

23

In [ ]:
#Name
#Year
#Version
#Price

In [ ]:
results[0].find('h2').get_text()

'Mercedes C 180 CABRIOLET'

In [ ]:
results[0].find('span', {'class': '_18b01e88'}).get_text()

'17,000 km'

In [ ]:
results[0].find('div', {'class': '_948d9e0a a9d78308 _371e9918'}).get_text()

'17,000 kmâ€¢2019'

In [ ]:
results[0].find('span', {'class': '_1f2a2b47'}).get_text()

'Rs 28,500,000'

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Initialize lists for Name, Year, Version, and Price
Name = []
Year = []
Version = []
Price = []

# Iterate through each result in results
for result in results:
    # Extract Name from the <h2> tag
    name_tag = result.find('h2')
    name_text = name_tag.get_text(strip=True) if name_tag else "N/A"
    Name.append(name_text)

    # Extract Year
    year_tag = result.find('span', {'class': '_18b01e88'})  # Replace 'year_class' with the actual class name
    year_text = year_tag.get_text(strip=True) if year_tag else "N/A"
    Year.append(year_text)

    # Extract Version
    version_tag = result.find('span', {'class': '_948d9e0a _36ddd253'})  # Replace 'version_class' with the actual class name
    version_text = version_tag.get_text(strip=True) if version_tag else "N/A"
    Version.append(version_text)

    # Extract Price
    price_tag = result.find('span', {'class': '_1f2a2b47'})  # Replace 'price_class' with the actual class name
    price_text = price_tag.get_text(strip=True) if price_tag else "N/A"
    Price.append(price_text)

# Create a DataFrame with the extracted data
data = {
    'Name': Name,
    'Year': Year,
    'Version': Version,
    'Price': Price
}
df = pd.DataFrame(data)

# Display the DataFrame
print(df)
"""df = pd.DataFrame(data)

# Save the DataFrame to an Excel file
df.to_excel('Data Mined.xlsx', index=False)

print("Data Mined.xlsx")
"""

                                                 Name        Year Version  \
0                            Mercedes C 180 CABRIOLET   17,000 km     N/A
1                       Hyundai Santro 2004 Executive        1 km     N/A
2                         Suzuki Wagon R  VXL 2020/21   90,000 km     N/A
3        Suzuki Wagon R model 2020 showroom condition        1 km     N/A
4                                 Suzuki Wagon R 2023   13,000 km     N/A
5                                    Toyota Vitz 2014   85,000 km     N/A
6                            Nissan Note E Power 2017   70,000 km     N/A
7              Suzuki Alto 2021 AGS VXL total genuine   17,000 km     N/A
8                                   Toyota Yaris 2023   19,000 km     N/A
9    Suzuki Swift 2012 Automatic original white color   69,000 km     N/A
10  Suzuki Swift 2010 original color auto transmis...   63,000 km     N/A
11  City 1.3 Excelent condition 16+ avg, well ment...  140,000 km     N/A
12                               Honda City IDSI 2007  132,000 km     N/A
13               Daihatsu Mira 2004 registration 2008  162,000 km     N/A
14                       Suzuki Cultus VXR 2008 model   75,000 km     N/A
15                             Suzuki Cultus VXR 2004  125,000 km     N/A
16                           Suzuki Alto Lapin 2021 L   16,200 km     N/A
17                                   Suzuki Alto 2021   13,000 km     N/A
18                           Mitsubishi Ek Wagon 2021    8,800 km     N/A
19                         Honda Civic Prosmetic 2008  107,106 km     N/A
20                          Toyota Corolla Altis 2018   80,000 km     N/A
21                            Daihatsu Boon 2006/2012  186,000 km     N/A
22                             Suzuki Cultus VXL 2019   65,000 km     N/A

            Price
0   Rs 28,500,000
1      Rs 775,000
2    Rs 2,545,000
3    Rs 2,590,000
4    Rs 2,960,000
5    Rs 2,675,000
6    Rs 4,190,000
7    Rs 2,670,000
8    Rs 4,550,000
9    Rs 2,130,000
10   Rs 2,070,000
11   Rs 2,650,000
12   Rs 1,850,000
13   Rs 1,400,000
14     Rs 920,000
15     Rs 900,000
16   Rs 3,150,000
17   Rs 3,190,000
18   Rs 3,325,000
19   Rs 2,280,000
20   Rs 4,560,000
21   Rs 2,000,000
22   Rs 3,050,000

'df = pd.DataFrame(data)\n\n# Save the DataFrame to an Excel file\ndf.to_excel(\'Retailers_Data_zero_point_websites.xlsx\', index=False)\n\nprint("Data has been saved to Mobile_Phones.xlsx")\n'

In [ ]:
import pandas as pd


# Find the maximum length of lists in the data dictionary
max_len = max(len(lst) for lst in data.values())

# Pad each list to the maximum length with 'n/a'
for key, lst in data.items():
    data[key] = lst + ['n/a'] * (max_len - len(lst))

# Create the DataFrame
df = pd.DataFrame(data)

# Save the DataFrame to an Excel file
df.to_excel('data mine of Cars.xlsx', index=False)

print("Data Mined.xlsx")

Data has been saved to data mine of Cars_websites.xlsx

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Lists to store the data
Name = []
Year = []
Version = []
Price = []

# Pagination loop for the first 13 pages
for i in range(1, 14):
    # Website URL with pagination
    website = f'your Website={i}'

    # Send an HTTP GET request to the website
    response = requests.get(website)

    # Check if the request was successful
    if response.status_code != 200:
        print(f"Failed to fetch page {i}. Status code: {response.status_code}")
        continue  # Skip to the next page if the current one fails

    # Parse the HTML content with BeautifulSoup
    soup = BeautifulSoup(response.content, 'html.parser')

    # Find all listings on the page
    results = soup.find_all('article', {'class': '_68441e28'})

    # Extract information from each listing
    for result in results:
        # Extract Name from the <h2> tag
        name_tag = result.find('h2')
        name_text = name_tag.get_text(strip=True) if name_tag else "N/A"
        Name.append(name_text)

        # Extract Year
        year_tag = result.find('span', {'class': '_18b01e88'})  # Adjust class name if necessary
        year_text = year_tag.get_text(strip=True) if year_tag else "N/A"
        Year.append(year_text)

        # Extract Version
        version_tag = result.find('span', {'class': '_948d9e0a _36ddd253'})  # Adjust class name if necessary
        version_text = version_tag.get_text(strip=True) if version_tag else "N/A"
        Version.append(version_text)

        # Extract Price
        price_tag = result.find('span', {'class': '_1f2a2b47'})  # Adjust class name if necessary
        price_text = price_tag.get_text(strip=True) if price_tag else "N/A"
        Price.append(price_text)

    print(f"Page {i} scraped successfully.")

# Create a DataFrame with the extracted data
data = {
    'Name': Name,
    'Year': Year,
    'Version': Version,
    'Price': Price
}
df = pd.DataFrame(data)

# Save the DataFrame to a CSV file
df.to_csv('Data Mined.csv', index=False)

print("Data scraping completed. Results saved to 'Data Mined.csv'.")

Page 1 scraped successfully.
Page 2 scraped successfully.
Page 3 scraped successfully.
Page 4 scraped successfully.
Page 5 scraped successfully.
Page 6 scraped successfully.
Page 7 scraped successfully.
Page 8 scraped successfully.
Page 9 scraped successfully.
Page 10 scraped successfully.
Page 11 scraped successfully.
Page 12 scraped successfully.
Page 13 scraped successfully.
Data scraping completed. Results saved to 'olx_vehicles.csv'.

In [ ]:

# Save the DataFrame to an Excel file
df.to_excel('data mine of Cars 4.xlsx', index=False)

print("Data has been saved to data mine of Cars 4_websites.xlsx")

Data has been saved to data mine of Cars 4_websites.xlsx